## Data Cleaning

## 1. Dataset walkthrough



In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('./movie_ratings_not_clean.txt')
df.head()

UserID  Braveheart  TheEnglishPatient  Titanic ShakespeareinLove  \
0  Olivia         3.0               40.0      2.0                 4   
1    Noah         3.0                5.0      5.0                 1   
2    Emma         2.0                1.0      3.0                 3   
3    Liam         0.0                1.0      3.0                 0   
4     Ava         3.0                4.0      2.0                 5   

  AmericanBeauty  Gladiator ABeautifulMind  Chicago  \
0            NaN        1.0              2      NaN   
1              3        4.0              0      NaN   
2              5        5.0              5      NaN   
3              3        5.0              1      NaN   
4              0       99.0              1      NaN   

   TheLordoftheRings:TheReturnoftheKing  MillionDollarBaby  Crash  \
0                                   2.0                4.0    3.0   
1                                   1.0                5.0    4.0   
2                                   3.0                3.0    0.0   
3                                   0.0                1.0    4.0   
4                                   NaN                5.0    5.0   

   TheDeparted  NoCountryforOldMen  SlumdogMillionaire  TheHurtLocker  
0          2.0                 5.0                 4.0              1  
1          3.0                 0.0                 0.0              2  
2          2.0                 4.0                 2.0              4  
3          1.0                 3.0                 3.0              3  
4          5.0                 1.0                 NaN              5

In [ ]:
df.describe()

Braveheart  TheEnglishPatient    Titanic  Gladiator  Chicago  \
count   42.000000          39.000000  47.000000  42.000000      0.0   
mean     2.761905           9.051282   2.659574   4.619048      NaN   
std      1.960706          32.019689   1.564228  15.003987      NaN   
min      0.000000           0.000000   0.000000   0.000000      NaN   
25%      1.000000           1.000000   1.000000   1.000000      NaN   
50%      3.000000           3.000000   3.000000   2.000000      NaN   
75%      4.000000           4.500000   4.000000   4.000000      NaN   
max      9.000000         200.000000   5.000000  99.000000      NaN   

       TheLordoftheRings:TheReturnoftheKing  MillionDollarBaby      Crash  \
count                             33.000000          47.000000  45.000000   
mean                               2.424242           2.851064   2.600000   
std                                1.750541           1.693706   1.656941   
min                                0.000000           0.000000   0.000000   
25%                                1.000000           1.500000   1.000000   
50%                                2.000000           3.000000   3.000000   
75%                                4.000000           4.000000   4.000000   
max                                5.000000           5.000000   5.000000   

       TheDeparted  NoCountryforOldMen  SlumdogMillionaire  TheHurtLocker  
count    40.000000           45.000000           47.000000      50.000000  
mean      2.325000            2.666667            2.489362       2.280000  
std       1.845125            1.809068            1.816259       1.750102  
min       0.000000            0.000000            0.000000       0.000000  
25%       0.750000            1.000000            1.000000       1.000000  
50%       2.000000            3.000000            3.000000       2.000000  
75%       4.000000            4.000000            4.000000       4.000000  
max       5.000000            5.000000            5.000000       5.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 16 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   UserID                                49 non-null     object 
 1   Braveheart                            42 non-null     float64
 2   TheEnglishPatient                     39 non-null     float64
 3   Titanic                               47 non-null     float64
 4   ShakespeareinLove                     44 non-null     object 
 5   AmericanBeauty                        44 non-null     object 
 6   Gladiator                             42 non-null     float64
 7   ABeautifulMind                        44 non-null     object 
 8   Chicago                               0 non-null      float64
 9   TheLordoftheRings:TheReturnoftheKing  33 non-null     float64
 10  MillionDollarBaby                     47 non-null     float64
 11  Crash                

## 2. Understanding Pandas methods

In [ ]:
users_df = pd.DataFrame({
    'UserID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

In [ ]:
purchases_df = pd.DataFrame({
    'UserID': [1, 1, 2],
    'Product': ['Book', 'Pen', 'Book']
})

In [ ]:
users_df

UserID     Name
0       1    Alice
1       2      Bob
2       3  Charlie

In [ ]:
purchases_df

UserID Product
0       1    Book
1       1     Pen
2       2    Book

### Merge df

In [ ]:
merged_df = pd.merge(users_df, purchases_df, on='UserID')
merged_df

UserID   Name Product
0       1  Alice    Book
1       1  Alice     Pen
2       2    Bob    Book

### Groupby

In [ ]:
purchase_counts = merged_df.groupby('Name').count()
purchase_counts

UserID  Product
Name                  
Alice       2        2
Bob         1        1

### Messy dataframe

In [ ]:
messy_df = pd.DataFrame({
    'user': ['Zoe', 'Liam', 'Mia', 'Liam'],
    'movie': ['A', 'B', 'C', 'B'],
    'rating': [5, 3, np.nan, 3]
})

In [ ]:
messy_df

user movie  rating
0   Zoe     A     5.0
1  Liam     B     3.0
2   Mia     C     NaN
3  Liam     B     3.0

### Drop NA

In [ ]:
dropped_na_df = messy_df.dropna()
dropped_na_df

user movie  rating
0   Zoe     A     5.0
1  Liam     B     3.0
3  Liam     B     3.0

### Fill NA

In [ ]:
filled_na_df = messy_df.fillna(value=0)
filled_na_df

user movie  rating
0   Zoe     A     5.0
1  Liam     B     3.0
2   Mia     C     0.0
3  Liam     B     3.0

### Drop Duplicates

In [ ]:
unique_df = messy_df.drop_duplicates()
unique_df

user movie  rating
0   Zoe     A     5.0
1  Liam     B     3.0
2   Mia     C     NaN

## 3. Cleaning the Dataset

In [ ]:
df.shape

(50, 16)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(50, 16)

In [ ]:
df.dropna(subset=['UserID'], inplace=True)

In [ ]:
df.shape

(49, 16)

In [ ]:
df.head()

UserID  Braveheart  TheEnglishPatient  Titanic ShakespeareinLove  \
0  Olivia         3.0               40.0      2.0                 4   
1    Noah         3.0                5.0      5.0                 1   
2    Emma         2.0                1.0      3.0                 3   
3    Liam         0.0                1.0      3.0                 0   
4     Ava         3.0                4.0      2.0                 5   

  AmericanBeauty  Gladiator ABeautifulMind  Chicago  \
0            NaN        1.0              2      NaN   
1              3        4.0              0      NaN   
2              5        5.0              5      NaN   
3              3        5.0              1      NaN   
4              0       99.0              1      NaN   

   TheLordoftheRings:TheReturnoftheKing  MillionDollarBaby  Crash  \
0                                   2.0                4.0    3.0   
1                                   1.0                5.0    4.0   
2                                   3.0                3.0    0.0   
3                                   0.0                1.0    4.0   
4                                   NaN                5.0    5.0   

   TheDeparted  NoCountryforOldMen  SlumdogMillionaire  TheHurtLocker  
0          2.0                 5.0                 4.0              1  
1          3.0                 0.0                 0.0              2  
2          2.0                 4.0                 2.0              4  
3          1.0                 3.0                 3.0              3  
4          5.0                 1.0                 NaN              5

In [ ]:
# First, ensure the column is numeric, converting errors to NaN
df['Braveheart'] = pd.to_numeric(df['Braveheart'], errors='coerce')

# Then, keep only the rows where the rating is 5 or less
cleaned_df = df[df['Braveheart'] <= 5]

In [ ]:
cleaned_df.describe()

Braveheart  TheEnglishPatient    Titanic  Gladiator  Chicago  \
count   40.000000          32.000000  38.000000  36.000000      0.0   
mean     2.600000          10.312500   2.710526   5.055556      NaN   
std      1.736486          35.295469   1.575280  16.189846      NaN   
min      0.000000           0.000000   0.000000   0.000000      NaN   
25%      1.000000           1.750000   2.000000   1.000000      NaN   
50%      3.000000           3.000000   3.000000   2.000000      NaN   
75%      4.000000           4.250000   4.000000   4.000000      NaN   
max      5.000000         200.000000   5.000000  99.000000      NaN   

       TheLordoftheRings:TheReturnoftheKing  MillionDollarBaby      Crash  \
count                             27.000000          37.000000  36.000000   
mean                               2.407407           2.864865   2.583333   
std                                1.715523           1.718561   1.645340   
min                                0.000000           0.000000   0.000000   
25%                                1.000000           1.000000   1.000000   
50%                                2.000000           3.000000   3.000000   
75%                                4.000000           4.000000   4.000000   
max                                5.000000           5.000000   5.000000   

       TheDeparted  NoCountryforOldMen  SlumdogMillionaire  TheHurtLocker  
count    31.000000           36.000000           37.000000      40.000000  
mean      1.967742            2.638889            2.648649       2.450000  
std       1.834555            1.759103            1.829029       1.753385  
min       0.000000            0.000000            0.000000       0.000000  
25%       0.000000            1.000000            1.000000       1.000000  
50%       2.000000            3.000000            3.000000       2.500000  
75%       3.500000            4.000000            4.000000       4.000000  
max       5.000000            5.000000            5.000000       5.000000

## 4. Numpy

### Speed

In [ ]:
import numpy as np
import time

In [ ]:
list_size = 1_000_000
python_list = list(range(list_size))
numpy_array = np.array(python_list)

In [ ]:
print("--- Using Python List ---")
start_time = time.time()

list_sum = 0
for number in python_list:
    list_sum += number

end_time = time.time()
list_duration = end_time - start_time
print(f"Sum: {list_sum}")
print(f"Time taken: {list_duration:.6f} seconds")

--- Using Python List ---
Sum: 499999500000
Time taken: 0.112150 seconds


In [ ]:
print("\n--- Using NumPy Array ---")
start_time = time.time()

numpy_sum = np.sum(numpy_array)

end_time = time.time()
numpy_duration = end_time - start_time
print(f"Sum: {numpy_sum}")
print(f"Time taken: {numpy_duration:.6f} seconds")


--- Using NumPy Array ---
Sum: 499999500000
Time taken: 0.001263 seconds


In [ ]:
print("\n--- Conclusion ---")
print(f"NumPy was {list_duration / numpy_duration:.2f} times faster.")


--- Conclusion ---
NumPy was 88.77 times faster.


### Mulit-dimensional arrays

In [ ]:
print("--- 1. One-Dimensional Array (Vector) ---")
# Like a single list
arr_1d = np.array([10, 20, 30, 40])
print(arr_1d)
print(f"Dimensions: {arr_1d.ndim}")
print(f"Shape: {arr_1d.shape}")
print(f"Accessing the second element: {arr_1d[1]}") # Prints 20

--- 1. One-Dimensional Array (Vector) ---
[10 20 30 40]
Dimensions: 1
Shape: (4,)
Accessing the second element: 20


In [ ]:
print("\n--- 2. Two-Dimensional Array (Matrix) ---")
# Like a spreadsheet or a grid (rows and columns)
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr_2d)
print(f"Dimensions: {arr_2d.ndim}")
print(f"Shape: {arr_2d.shape}")
print(f"Accessing element at row 1, column 2: {arr_2d[1, 2]}")


--- 2. Two-Dimensional Array (Matrix) ---
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Accessing element at row 1, column 2: 6


In [ ]:
print("\n--- 3. Three-Dimensional Array (Tensor) ---")
# Like a cube of data or a collection of matrices
arr_3d = np.array([
    [[1, 2], [3, 4]],    # First 2D matrix (depth 0)
    [[5, 6], [7, 8]]     # Second 2D matrix (depth 1)
])
print(arr_3d)
print(f"Dimensions: {arr_3d.ndim}")
print(f"Shape: {arr_3d.shape}")
print(f"Accessing element at depth 1, row 0, column 1: {arr_3d[1, 0, 1]}")


--- 3. Three-Dimensional Array (Tensor) ---
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)
Accessing element at depth 1, row 0, column 1: 6
